version: "2"
services:
  jsm_rabbitmq:
    container_name: jsm_rabbitmq
    image: "rabbitmq:management"
    environment:
      - RABBITMQ_DEFAULT_USER=jsm
      - RABBITMQ_DEFAULT_PASS=jsm
    ports:
      - "5672:5672"
      - "15672:15672"
  jsm_mongodb:
    container_name: jsm_mongodb
    image: mongo
    volumes:
      - /home/mongo/data:/data/db
      - /home/mongo/backups:/backups
    ports:
      - "27017:27017"