version: "2"
services:
  redis:
    container_name: redis
    image: redis
    ports:
        - "6379"
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - /home/mongo/data:/data/db
      - /home/mongo/backups:/backups
    ports:
      - "27017"
  cross:
    container_name: cross
    restart: unless-stopped
    build: .
    ports:
      - "8080"
    links:
      - mongodb:crossdb
      - redis:redis
  nginx:
    build: ./VCross
    container_name: nginx-vcross
    links:
        - cross:cross
    ports:
        - "80:80"