version: "2"
services:
  cross:
    container_name: cross
    restart: unless-stopped
    build: .
    ports:
      - "9001:9001"
    links:
      - mongodb:crossdb
      - redis:redis
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - /home/mongo/data:/data/db
      - /home/mongo/backups:/backups
    ports:
      - "27017:27017"