FROM node:latest as vcross-stage

WORKDIR /app
RUN ll
COPY /home/jsmtest/apps/VCross/package*.json ./
RUN npm install
COPY /home/jsmtest/apps/VCross .
RUN npm run build

FROM nginx:latest as build-stage
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=vcross-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]



