FROM node:latest as vcross-stage
WORKDIR /app
COPY ../VCross/package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx as build-stage
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=vcross-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]



